# Generated by Django 5.1.3 on 2024-11-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='register',
            managers=[
            ],
        ),
    ]
