# Generated by Django 5.1.3 on 2024-11-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_register_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='lanme',
            new_name='lname',
        ),
    ]
