# Generated by Django 5.1.3 on 2024-11-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='city',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='name',
            new_name='lname',
        ),
        migrations.RemoveField(
            model_name='ninja',
            name='state',
        ),
    ]
