# Generated by Django 5.1.3 on 2024-11-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_rename_city_ninja_fname_rename_name_ninja_lname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
